#!/usr/bin/env python3
import os
import sys
import time
import argparse
import json
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

# Cargar variables de entorno desde el archivo de configuración de Layer_3
env_path = Path(__file__).resolve().parent.parent.parent / "Layer_3" / "config" / "layer_3.env"

try:
    from dotenv import load_dotenv
    load_dotenv(env_path)
except ImportError:
    # Fallback: leer el archivo .env manualmente si dotenv no está disponible
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    value = value.strip()
                    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
                        value = value[1:-1]
                    os.environ[key.strip()] = value

# --- CONFIGURACIÓN Y CONSTANTES ---
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

DEFAULT_MODEL = "ollama"
GROQ_MODEL = "llama-3.3-70b-versatile"
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Ollama (local)
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:3b")
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_TIMEOUT_SEC = int(os.getenv("OLLAMA_TIMEOUT_SEC", "120"))
OLLAMA_API_URL = f"{OLLAMA_HOST}/v1/chat/completions"

MAX_CHARS_PER_CHUNK = 10000

SUMMARY_SYSTEM = """Eres un sintetizador de información experto en el ecosistema VANTAGE.
Tu objetivo es procesar transcripciones o documentos técnicos y formatear el resultado estrictamente bajo el esquema del skill 'vantage-present-handoff' (Handoff Lite)."""

SUMMARY_PROMPT = """Procesa la siguiente transcripción o texto y genera la salida usando EXACTAMENTE el formato de Handoff Lite.

METADATOS DE CONTEXTO:
- Serial: {serial}
- Agent Family/Instance: {agent_family}/{agent_instance}
- Session ID: {session_id}
- Timestamp CDMX: {timestamp_cdmx}

FORMATO REQUERIDO (Respeta los bloques de código y la estructura exacta):

HANDING OFF...

```yaml
handoff:
  serial: {serial}
  schema_version: "1.0"
  generated_at: "{timestamp_cdmx}"
  timezone: America/Mexico_City
  generator:
    family: {agent_family}
    instance: {agent_instance}
  source_session:
    session_id: {session_id}
    ledger_status: OPEN
  parent_handoff:
    serial: null
  skill:
    loaded: true
    name: vantage-present-handoff
  status: DELIVERED
```

## S0 — Timestamp

`{timestamp_cdmx} CDMX`

## S1 — Identidad e IDs

`{serial} | {agent_family}/{agent_instance} | {session_id} | Ledger: OPEN`

## S2 — Pendientes

(Máximo 5 pendientes críticos identificados en el texto. Usa bullets)

## S3 — Heredados

(Deuda técnica, bloqueadores o acuerdos heredados que afecten la continuidad)

## S4 — Última acción

(Síntesis ejecutiva de los hitos o decisiones procesadas en esta sesión)

### S4-EVIDENCE (obligatorio si aplica)

(Si el texto contiene comandos o verificaciones explícitas, inclúyelos aquí. De lo contrario, indica N/A o UNVERIFIED según la regla del esquema)

## S5 — Contexto

`VANTAGE: v1.1.0 | Skill: vantage-present-handoff | Sync: PASS`

```text
HANDOFF DELIVERED
Serial: {serial}
Generated by: {agent_family}/{agent_instance}
Session: {session_id}
```

---
TEXTO A PROCESAR:
{transcript}
"""

# --- LLM CLIENTS ---

def call_ollama(prompt: str) -> str:
    headers = {"Content-Type": "application/json"}
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": SUMMARY_SYSTEM},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.2
    }
    req = urllib.request.Request(
        OLLAMA_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as response:
            response_data = json.loads(response.read().decode("utf-8"))
            return response_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"Ollama API error {e.code}: {error_body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Ollama API connection error: {e}") from e

def call_groq(prompt: str) -> str:
    if not GROQ_API_KEY:
        raise RuntimeError("Falta GROQ_API_KEY en el entorno o .env")

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SUMMARY_SYSTEM},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.2
    }
    req = urllib.request.Request(
        GROQ_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            response_data = json.loads(response.read().decode("utf-8"))
            return response_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"Groq API error {e.code}: {error_body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Groq API connection error: {e}") from e

def call_gemini(prompt: str) -> str:
    from google import genai
    from google.genai import types

    if not GEMINI_API_KEY:
        raise RuntimeError("Falta GEMINI_API_KEY en el entorno o .env")

    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SUMMARY_SYSTEM,
            temperature=0.2,
        ),
    )
    return response.text

# --- HELPERS ---

def _hard_split(text: str, max_chars: int) -> list[str]:
    """Parte un texto que por sí solo excede max_chars (párrafo gigante)."""
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)]


def chunk_text(text: str, max_chars: int = MAX_CHARS_PER_CHUNK) -> list[str]:
    if len(text) <= max_chars:
        return [text]

    paragraphs = text.split("\n\n")
    chunks = []
    current_chunk = []
    current_len = 0

    for para in paragraphs:
        # Un párrafo sin \n\n puede ser mayor al límite (p. ej. un log o una
        # transcripción en una sola línea): antes se emitía completo y el chunk
        # superaba max_chars, rompiendo el troceo.
        if len(para) > max_chars:
            if current_chunk:
                chunks.append("\n\n".join(current_chunk))
                current_chunk = []
                current_len = 0
            chunks.extend(_hard_split(para, max_chars))
            continue

        if current_len + len(para) + 2 > max_chars:
            if current_chunk:
                chunks.append("\n\n".join(current_chunk))
            current_chunk = [para]
            current_len = len(para)
        else:
            current_chunk.append(para)
            current_len += len(para) + 2

    if current_chunk:
        chunks.append("\n\n".join(current_chunk))

    return chunks

def summarize(text: str, model: str = DEFAULT_MODEL, serial: str = "HO-000000", agent_family: str = "AGENT_FAMILY", agent_instance: str = "AGENT_INSTANCE", session_id: str = "SESSION-UNKNOWN") -> str:
    chunks = chunk_text(text)
    summaries = []
    timestamp_cdmx = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    for i, chunk in enumerate(chunks, 1):
        print(f"  → Enviando chunk {i}/{len(chunks)} ({len(chunk)} chars) a {model}...")
        prompt = SUMMARY_PROMPT.format(
            transcript=chunk,
            serial=serial,
            agent_family=agent_family,
            agent_instance=agent_instance,
            session_id=session_id,
            timestamp_cdmx=timestamp_cdmx
        )

        try:
            if model == "gemini":
                part = call_gemini(prompt)
            elif model == "ollama":
                part = call_ollama(prompt)
            else:
                part = call_groq(prompt)
            summaries.append(part)
        except Exception as e:
            if model == "gemini":
                print(f"  ⚠ Gemini falló ({e}). Intentando fallback a Ollama...")
                part = call_ollama(prompt)
                summaries.append(part)
            elif model == "ollama":
                print(f"  ⚠ Ollama falló ({e}). Reintentando chunk...")
                time.sleep(5)
                part = call_ollama(prompt)
                summaries.append(part)
            else:
                raise

        if i < len(chunks):
            time.sleep(2)

    if len(summaries) == 1:
        return summaries[0]

    print("  → Combinando resúmenes parciales en esquema Handoff Lite...")
    combined = "\n\n---\n\n".join(summaries)
    meta_prompt = SUMMARY_PROMPT.format(
        transcript=f"Estos son resúmenes parciales de una misma sesión larga. Consolídalos en un único Handoff Lite coherente sin duplicar información:\n\n{combined}",
        serial=serial,
        agent_family=agent_family,
        agent_instance=agent_instance,
        session_id=session_id,
        timestamp_cdmx=timestamp_cdmx
    )

    if model == "gemini":
        try:
            return call_gemini(meta_prompt)
        except Exception as e:
            print(f"  ⚠ Gemini falló en meta-resumen ({e}). Fallback a Ollama...")
            return call_ollama(meta_prompt)
    elif model == "ollama":
        try:
            return call_ollama(meta_prompt)
        except Exception as e:
            print(f"  ⚠ Ollama falló en meta-resumen ({e}). Fallback a Groq...")
            return call_groq(meta_prompt)

    return call_groq(meta_prompt)

# --- CLI & EXECUTION ---

def process_one(filepath: str, output: str = None, model: str = DEFAULT_MODEL, serial: str = "HO-000000", agent_family: str = "VANTAGE", agent_instance: str = "CLI", session_id: str = None):
    path = Path(filepath)
    if not path.exists():
        print(f"Error: El archivo {filepath} no existe.", file=sys.stderr)
        sys.exit(1)

    if not session_id:
        session_id = f"SESSION-{datetime.now().strftime('%Y%m%d')}-1"

    with open(path, "r", encoding="utf-8") as f:
        full_text = f.read()

    print(f"\n📄 Procesando: {path}")
    print(f"  → Total caracteres: {len(full_text)}")

    summary = summarize(
        full_text,
        model=model,
        serial=serial,
        agent_family=agent_family,
        agent_instance=agent_instance,
        session_id=session_id
    )

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(summary)
        print(f"✓ Handoff guardado en: {out_path}")
    else:
        print("\n" + "=" * 40 + "\n")
        print(summary)
        print("\n" + "=" * 40)

def main():
    parser = argparse.ArgumentParser(description="vsum: Generador de handoffs estructurados bajo el esquema VANTAGE")
    parser.add_argument("file", help="Ruta al archivo Markdown o de texto a procesar")
    parser.add_argument("-o", "--output", help="Ruta de archivo de salida (opcional)")
    parser.add_argument("-m", "--model", choices=["ollama", "groq", "gemini"], default=DEFAULT_MODEL, help="Modelo a utilizar (ollama por defecto)")
    parser.add_argument("-s", "--serial", default="HO-000000", help="Serial del Handoff (ej. HO-000123)")
    parser.add_argument("--family", default="VANTAGE", help="Familia del agente emisor")
    parser.add_argument("--instance", default="CLI", help="Instancia del agente emisor")
    parser.add_argument("--session", help="ID de sesión (ej. SESSION-20260928-1)")

    args = parser.parse_args()
    process_one(
        args.file,
        output=args.output,
        model=args.model,
        serial=args.serial,
        agent_family=args.family,
        agent_instance=args.instance,
        session_id=args.session
    )

if __name__ == "__main__":
    main()
