#!/usr/bin/env python3
import os
import sys
import time
import argparse
import json
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

# Cargar variables de entorno desde el archivo de configuración de Layer_3
env_path = Path(__file__).resolve().parent.parent.parent / "Layer_3" / "config" / "layer_3.env"

try:
    from dotenv import load_dotenv
    load_dotenv(env_path)
except ImportError:
    # Fallback: leer el archivo .env manualmente si dotenv no está disponible
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    value = value.strip()
                    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
                        value = value[1:-1]
                    os.environ[key.strip()] = value

# --- CONFIGURACIÓN Y CONSTANTES ---
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

DEFAULT_MODEL = "ollama"
GROQ_MODEL = "llama-3.3-70b-versatile"
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Ollama (local)
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:3b")
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_TIMEOUT_SEC = int(os.getenv("OLLAMA_TIMEOUT_SEC", "120"))
OLLAMA_API_URL = f"{OLLAMA_HOST}/v1/chat/completions"

MAX_CHARS_PER_CHUNK = 10000

SUMMARY_SYSTEM = """Eres un sintetizador de información experto en el ecosistema VANTAGE.
Tu objetivo es procesar transcripciones o documentos técnicos y formatear el resultado estrictamente bajo el esquema del skill 'vantage-present-handoff' (Handoff Lite)."""

SUMMARY_PROMPT = """Procesa la siguiente transcripción o texto y genera la salida usando EXACTAMENTE el formato de Handoff Lite.

METADATOS DE CONTEXTO:
- Serial: {serial}
- Agent Family/Instance: {agent_family}/{agent_instance}
- Session ID: {session_id}
- Timestamp CDMX: {timestamp_cdmx}

FORMATO REQUERIDO (Respeta los bloques de código y la estructura exacta):

HANDING OFF...

```yaml
handoff:
  serial: {serial}
  schema_version: "1.0"
  generated_at: "{timestamp_cdmx}"
  timezone: America/Mexico_City
  generator:
    family: {agent_family}
    instance: {agent_instance}
  source_session:
    session_id: {session_id}
    ledger_status: OPEN
  parent_handoff:
    serial: null
  skill:
    loaded: true
    name: vantage-present-handoff
  status: DELIVERED
```

## S0 — Timestamp

`{timestamp_cdmx} CDMX`

## S1 — Identidad e IDs

`{serial} | {agent_family}/{agent_instance} | {session_id} | Ledger: OPEN`

## S2 — Pendientes

(Máximo 5 pendientes críticos identificados en el texto. Usa bullets)

## S3 — Heredados

(Deuda técnica, bloqueadores o acuerdos heredados que afecten la continuidad)

## S4 — Última acción

(Síntesis ejecutiva de los hitos o decisiones procesadas en esta sesión)

### S4-EVIDENCE (obligatorio si aplica)

(Si el texto contiene comandos o verificaciones explícitas, inclúyelos aquí. De lo contrario, indica N/A o UNVERIFIED según la regla del esquema)

## S5 — Contexto

`VANTAGE: v1.1.0 | Skill: vantage-present-handoff | Sync: PASS`

```text
HANDOFF DELIVERED
Serial: {serial}
Generated by: {agent_family}/{agent_instance}
Session: {session_id}
```

---
TEXTO A PROCESAR:
{transcript}
"""

# --- LLM CLIENTS ---

def call_ollama(prompt: str) -> str:
    headers = {"Content-Type": "application/json"}
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": SUMMARY_SYSTEM},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.2
    }
    req = urllib.request.Request(
        OLLAMA_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=OLLAMA_TIMEOUT_SEC) as response:
            response_data = json.loads(response.read().decode("utf-8"))
            return response_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"Ollama API error {e.code}: {error_body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Ollama API connection error: {e}") from e

def call_groq(prompt: str) -> str:
    if not GROQ_API_KEY:
        raise RuntimeError("Falta GROQ_API_KEY en el entorno o .env")

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SUMMARY_SYSTEM},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.2
    }
    req = urllib.request.Request(
        GROQ_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            response_data = json.loads(response.read().decode("utf-8"))
            return response_data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"Groq API error {e.code}: {error_body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Groq API connection error: {e}") from e

def call_gemini(prompt: str) -> str:
    from google import genai
    from google.genai import types

    if not GEMINI_API_KEY:
        raise RuntimeError("Falta GEMINI_API_KEY en el entorno o .env")

    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SUMMARY_SYSTEM,
            temperature=0.2,
        ),
    )
    return response.text

# --- HELPERS ---

def _hard_split(text: str, max_chars: int) -> list[str]:
    """Parte un texto que por sí solo excede max_chars (párrafo gigante)."""
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)]


def chunk_text(text: str, max_chars: int = MAX_CHARS_PER_CHUNK) -> list[str]:
    if max_chars <= 0:
        raise ValueError("max_chars debe ser positivo")
    if len(text) <= max_chars:
        return [text]

    paragraphs = text.split("\n\n")
    chunks = []
    current_chunk = []
    current_len = 0

    for para in paragraphs:
        # Un párrafo sin \n\n puede ser mayor al límite (p. ej. un log o una
        # transcripción en una sola línea): antes se emitía completo y el chunk
        # superaba max_chars, rompiendo el troceo.
        if len(para) > max_chars:
            if current_chunk:
                chunks.append("\n\n".join(current_chunk))
                current_chunk = []
                current_len = 0
            chunks.extend(_hard_split(para, max_chars))
            continue

        separator_len = 2 if current_chunk else 0
        if current_len + len(para) + separator_len > max_chars:
            if current_chunk:
                chunks.append("\n\n".join(current_chunk))
            current_chunk = [para]
            current_len = len(para)
        else:
            current_chunk.append(para)
            current_len += len(para) + separator_len

    if current_chunk:
        chunks.append("\n\n".join(current_chunk))

    return chunks

def call_with_fallback(prompt: str, model: str) -> str:
    """Misma política para chunks y consolidación: Gemini → Ollama (2) → Groq.

    Groq sólo se usa como fallback si hay clave configurada.
    """
    if model == "groq":
        return call_groq(prompt)
    if model not in {"gemini", "ollama"}:
        raise ValueError(f"Modelo desconocido: {model}")
    if model == "gemini":
        try:
            return call_gemini(prompt)
        except Exception as e:
            print(f"  ⚠ Gemini falló ({e}). Intentando Ollama...")
    for attempt in range(2):
        try:
            return call_ollama(prompt)
        except Exception:
            if attempt == 0:
                print("  ⚠ Ollama falló. Reintentando en 5 segundos...")
                time.sleep(5)
            elif not GROQ_API_KEY:
                raise
    print("  ⚠ Ollama falló dos veces. Fallback al servicio externo Groq...")
    return call_groq(prompt)


def summarize(text: str, model: str = DEFAULT_MODEL, serial: str = "HO-000000", agent_family: str = "AGENT_FAMILY", agent_instance: str = "AGENT_INSTANCE", session_id: str = "SESSION-UNKNOWN") -> str:
    metadata = dict(
        serial=serial, agent_family=agent_family, agent_instance=agent_instance,
        session_id=session_id, timestamp_cdmx=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )
    # El presupuesto incluye las instrucciones y metadatos, no sólo el texto.
    # Es un límite de caracteres conservador, no una medida exacta de tokens.
    overhead = len(SUMMARY_SYSTEM) + len(SUMMARY_PROMPT.format(transcript="", **metadata))
    budget = MAX_CHARS_PER_CHUNK - overhead
    meta_instruction = (
        "Estos son resúmenes parciales de una misma sesión larga. Consolídalos "
        "sin duplicar información en un Handoff Lite breve. Reduce el texto "
        "a menos de la mitad conservando decisiones, pendientes y evidencia:\n\n"
    )
    meta_budget = budget - len(meta_instruction)
    if meta_budget <= 0:
        raise ValueError("Las instrucciones y metadatos exceden el presupuesto de contexto")

    def request(transcript):
        prompt = SUMMARY_PROMPT.format(transcript=transcript, **metadata)
        result = call_with_fallback(prompt, model)
        if not isinstance(result, str) or not result.strip():
            raise RuntimeError("El modelo devolvió un resumen vacío")
        return result

    chunks = chunk_text(text, budget)
    summaries = []
    for i, chunk in enumerate(chunks, 1):
        print(f"  → Enviando chunk {i}/{len(chunks)} ({len(chunk)} chars) a {model}...")
        summaries.append(request(chunk))
        if i < len(chunks):
            time.sleep(2)

    if len(summaries) == 1:
        return summaries[0]

    combined = "\n\n---\n\n".join(summaries)
    # Map/reduce jerárquico sin truncar. Fallar explícitamente si el modelo no
    # comprime, en lugar de un bucle infinito o una llamada fuera de presupuesto.
    for level in range(8):
        print(f"  → Consolidando resúmenes parciales (nivel {level + 1})...")
        groups = chunk_text(combined, meta_budget)
        reduced = [request(meta_instruction + group) for group in groups]
        if len(reduced) == 1:
            return reduced[0]
        next_combined = "\n\n---\n\n".join(reduced)
        if len(next_combined) >= len(combined):
            raise RuntimeError("La consolidación no reduce el texto; no se enviará un prompt sobredimensionado")
        combined = next_combined
    raise RuntimeError("La consolidación excedió el máximo de 8 niveles")

# --- CLI & EXECUTION ---

def process_one(filepath: str, output: str = None, model: str = DEFAULT_MODEL, serial: str = "HO-000000", agent_family: str = "VANTAGE", agent_instance: str = "CLI", session_id: str = None):
    path = Path(filepath)
    if not path.exists():
        print(f"Error: El archivo {filepath} no existe.", file=sys.stderr)
        sys.exit(1)

    if not session_id:
        session_id = f"SESSION-{datetime.now().strftime('%Y%m%d')}-1"

    with open(path, "r", encoding="utf-8") as f:
        full_text = f.read()

    print(f"\n📄 Procesando: {path}")
    print(f"  → Total caracteres: {len(full_text)}")

    summary = summarize(
        full_text,
        model=model,
        serial=serial,
        agent_family=agent_family,
        agent_instance=agent_instance,
        session_id=session_id
    )

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(summary)
        print(f"✓ Handoff guardado en: {out_path}")
    else:
        print("\n" + "=" * 40 + "\n")
        print(summary)
        print("\n" + "=" * 40)

def main():
    parser = argparse.ArgumentParser(description="vsum: Generador de handoffs estructurados bajo el esquema VANTAGE")
    parser.add_argument("file", help="Ruta al archivo Markdown o de texto a procesar")
    parser.add_argument("-o", "--output", help="Ruta de archivo de salida (opcional)")
    parser.add_argument("-m", "--model", choices=["ollama", "groq", "gemini"], default=DEFAULT_MODEL, help="Modelo a utilizar (ollama por defecto)")
    parser.add_argument("-s", "--serial", default="HO-000000", help="Serial del Handoff (ej. HO-000123)")
    parser.add_argument("--family", default="VANTAGE", help="Familia del agente emisor")
    parser.add_argument("--instance", default="CLI", help="Instancia del agente emisor")
    parser.add_argument("--session", help="ID de sesión (ej. SESSION-20260928-1)")

    args = parser.parse_args()
    process_one(
        args.file,
        output=args.output,
        model=args.model,
        serial=args.serial,
        agent_family=args.family,
        agent_instance=args.instance,
        session_id=args.session
    )

if __name__ == "__main__":
    main()
